os: Visual Studio 2017

build_script:
  - cmd: .\build.cmd

test: off

cache:
  - "%LocalAppData%\\NuGet\\Cache -> paket.lock"
  - "node_modules -> yarn.lock"

artifacts:
  - path: release
    name: Fable Transpilation Artifacts